[package]
name = "slap"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["full"] }
tower-lsp = "0.20.0"
tracing-subscriber = "0.3.18"
